# config
cover: /dev-ra/img/cover.png
icon: /dev-ra/img/icon.png
logo: /dev-ra/img/logo-redealumni.png
bio: 'Desenvolvedor RedeAlumni'

# Content
excerpt_link: Continue lendo

# Miscellaneous
rss:
google_analytics: UA-57485401-1
